<ul id="menu">
	<li><a href="<?php echo $this->baseUrl(); ?>/atividades">Lista de atividades</a></li>
	<li><a href="<?php echo $this->baseUrl(); ?>/atividades/formulario">Submeter proposta de trabalho</a></li>
	<hr />
</ul>

<?php if(!empty($this->atividadesSubmetidas) && count($this->atividadesSubmetidas)) { ?>
<hr />
<div>
<p align="center">
<h2 style="padding-left:25px">Atividades Submetidas</h2>
</p>
<?php echo $this->partial( 'atividades/partial-listagem.phtml', array( 'atividades' => $this->atividadesSubmetidas, 'vagasOcupadas' => $this->vagasOcupadas)); ?>
</div>
<?php } ?>
<hr />
<div>

<h2 style="padding-left:25px">Atividades que você esta inscrito(a)</h2>
<?php if(!empty($this->atividadesInscrito) && count($this->atividadesInscrito)) { ?>
<?php echo $this->partial( 'atividades/partial-listagem.phtml', array( 'atividades' => $this->atividadesInscrito, 'vagasOcupadas' => $this->vagasOcupadas, 'listagemAtividadesInscritas'	=>	true)); ?>
<a style="padding-right:25px; float:right;" href="<?php echo $this->baseUrl(); ?>/atividades">Me inscrever mais atividades</a>
<?php } else { ?>
<b>Você não esta inscrito(a) em nenhuma atividade, caso queira se inscrever acesse a
<a href="<?php echo $this->baseUrl(); ?>/atividades">lista de atividades</a>.</b>
<?php } ?>
</div>