<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<title>FLISOL 2010 - Sistema de inscrições</title>
		<meta http-equiv="Content-Type" content="application/xhtml; charset=UTF-8" />
	</head>
	<body>
		<p>Seja bem vindo(a), <?php echo $this->nomeParticipanteEmail; ?> ao Festival Latinoamericano de instalação de software livre 2010</p>
	</body>
</html>